services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/dockerfile.production
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    depends_on:
      - http-server
      - ws-server

  migrate:
    build:
      context: .
      dockerfile: apps/http-server/dockerfile.production
    container_name: migrate
    command: >
      sh -c "pnpm --filter db run prisma:migrate"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - db

  http-server:
    build:
      context: .
      dockerfile: apps/http-server/dockerfile.production
    container_name: http-server
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - migrate

  ws-server:
    build:
      context: .
      dockerfile: apps/ws-server/dockerfile.production
    container_name: ws-server
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - migrate

volumes:
  pgdata: